Repository Apra-Labs/ApraPipes, pull requests merged in 2023-08, with the labels that each got.

#270 TestSignalGenerator Module
  .github/workflows/build-test-lin-container.yml
  .github/workflows/build-test-lin-wsl.yml
  .github/workflows/build-test-lin.yml
  .github/workflows/build-test-win.yml
  base/CMakeLists.txt
  base/include/TestSignalGeneratorSrc.h
  base/src/TestSignalGeneratorSrc.cpp
  base/test/testSignalGeneratorSrc_tests.cpp
  base/test/test_utils.cpp
  data/TestSample.raw
  data/TestSample1.raw
  data/TestSample2.raw
Labels: Feature

#294 Mp4Reader getSetProps enhancement
  base/include/Mp4ReaderSource.h
  base/src/Mp4ReaderSource.cpp
  base/test/mp4readersource_tests.cpp
Labels: enhancement

#267 MotionExtractor module bug fix
  base/src/MotionVectorExtractor.cpp
Labels: bug

#242 1. Added motion vector as 2nd output from the H264EncoderV4l2 module.
  base/CMakeLists.txt
  base/include/H264EncoderV4L2.h
  base/include/H264EncoderV4L2Helper.h
  base/src/H264EncoderV4L2.cpp
  base/src/H264EncoderV4L2Helper.cpp
  base/test/h264encoderv4l2_tests.cpp
  base/test/h264encoderv4l2helper_tests.cpp
Labels: enhancement
